---
configuration_directory: "%{cwd}/spec/unit/infra/prerequisites"
state_file: "%{cwd}/state/prerequisites.tfstate"
vars:
  region: "%{hiera('region')}"

  user_1_name: "test-1-%{hiera('deployment_identifier')}"
  user_2_name: "test-2-%{hiera('deployment_identifier')}"
  user_3_name: "test-3-%{hiera('deployment_identifier')}"
